import type { components } from './api.generated'
type S = components['schemas']
export type Project = S['ProjectView']
export type Chapter = S['ChapterView']
export type Workflow = S['WorkflowView']
export type Gate = S['GateView']
export type Brief = S['BriefView']
export type Plan = S['PlanView']
export type Planning = S['PlanningView']
export type PlanningHistory = S['HistoryView']
export type Review = S['ReviewView']
export type Draft = S['ChapterVersionView']
export type Writing = S['WritingGenerationView']
export type Task = S['AgentTaskView']
export type ExecutionConfig = S['AgentExecutionConfigView']
export type Run = S['AgentRunView']
export type Transition = S['TransitionView']
export type Context = S['ContextInspection']
export type Lineage = S['PromptLineageView']
export type Dispatch = S['DispatchView']
export type Decision = 'APPROVE' | 'REJECT' | 'REQUEST_ALTERNATIVE' | 'MODIFY'

export type QualityReview = S['QualityReviewView']
export type Revision = S['RevisionView']
