from enum import StrEnum


class Status(StrEnum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"
    ACTIVE = "ACTIVE"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"
    DEPRECATED = "DEPRECATED"
    CANCELLED = "CANCELLED"
    EXECUTED = "EXECUTED"
    ARCHIVED = "ARCHIVED"


class Authority(StrEnum):
    A0_SYSTEM_RULE = "A0_SYSTEM_RULE"
    A1_USER_LOCKED = "A1_USER_LOCKED"
    A2_USER_APPROVED = "A2_USER_APPROVED"
    A3_CANON = "A3_CANON"
    A4_APPROVED_PLAN = "A4_APPROVED_PLAN"
    A5_USER_PREFERENCE = "A5_USER_PREFERENCE"
    A6_DERIVED_MEMORY = "A6_DERIVED_MEMORY"
    A7_AI_INFERENCE = "A7_AI_INFERENCE"


class ActorType(StrEnum):
    USER = "USER"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class ObjectType(StrEnum):
    PROJECT = "PROJECT"
    REQUIREMENT = "REQUIREMENT"
    DECISION = "DECISION"
    CHAPTER = "CHAPTER"
    CHAPTER_PLAN = "CHAPTER_PLAN"
    CHAPTER_VERSION = "CHAPTER_VERSION"
    LOCK = "LOCK"
    AUDIT_RECORD = "AUDIT_RECORD"


class RequirementType(StrEnum):
    MUST = "MUST"
    SHOULD = "SHOULD"
    PREFERENCE = "PREFERENCE"
    FORBIDDEN = "FORBIDDEN"
    QUALITY_EXPECTATION = "QUALITY_EXPECTATION"
    PRESERVE = "PRESERVE"
    CHANGE_REQUEST = "CHANGE_REQUEST"


class ScopeType(StrEnum):
    PROJECT = "PROJECT"
    CHAPTER = "CHAPTER"


class AuditAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    ARCHIVE = "ARCHIVE"
    VERSION_CREATE = "VERSION_CREATE"
    APPROVE = "APPROVE"
    SUPERSEDE = "SUPERSEDE"
    LOCK = "LOCK"
    UNLOCK = "UNLOCK"
